#define OutA_Red	GPIOC, GPIO_PIN_6
#define OutB_Black	GPIOC, GPIO_PIN_7
#define Led			GPIOA, GPIO_PIN_3
#define Button1		GPIOD, GPIO_PIN_2
#define Button2		GPIOD, GPIO_PIN_3
#define ParkingSwitch	GPIOC, GPIO_PIN_3
#define ClosedSwitch	GPIOC, GPIO_PIN_4
#define In3				GPIOC, GPIO_PIN_5
#define PushedSwitch	GPIOB, GPIO_PIN_4